apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:rvABixs08wSk/cIppKqW3S/hdWO8g+yDQ8xCemFB9gNYDbUm,iv:PHHwjLA9sORcAty1SdfjjPBbA/XRoTKzjTfXfbf7VBE=,tag:LRSROEqYNZfCsYO9eE+WMw==,type:str]
    credentials.json: ENC[AES256_GCM,data:MwhBRq4Jd3IXzfF0v/OgkIco9ulwz0WM6vOwR4HdNxSpDuozcl4i93yCJd95RFHG/y+9wQqtKrhSnpnRfUdadIGkeVxdd8QH+3shNAvuNjc9FtZDZ+htsgSSHkFtFo2LlbIZQXPcJJ6MjTdQkAggr8DszBsVmr8UNEkKOtudlWxctG16gL8A7tjM9NNhx30xMJ3kcQAee3Y59TWhP/Xu0OEDNRdovBw0fQiYZx7HJQ==,iv:04UFHsju5AhfHN7iUsB/uz6nc5PwI3mtvjDKyPT4jYc=,tag:dP8aLo/UkLFoHGUbKxnC5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dn0elwr6a32pdjspgz733zgwdmyur98wcmcadhdhkzwudp7g4uuq8ty9ff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOExWWVpKaVVJNWNMTHR2
            VnFnYWFkckVaTU5vand2N1h1bFRZWFlocWdNCkh2RkFaNDF4WjFLUVh0aitaRTVW
            dC9FaGxJVEo1ZlpxVHRPckFSTWlIbUUKLS0tIEZrSDZoWVJUQlZndFR2M1ZzTVNT
            bXhhUEY5Z0hLQ3FyOC9xeHdSRVdlbGMKM236RCEJJne0JIrQLk/BudvYPT0GCtYY
            HZhjiznY9x76Nntb0M0ihIFO67NVeWp4cs4i7TqOBqPhrAZIXHmY3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T12:45:10Z"
    mac: ENC[AES256_GCM,data:z9rgCHhCM+ICr2Yo9W8JnGSuSCuk/FwTr+2n1YFxzjwXHhFogTra1a2a8LKl+k0KpEVgO4AbTyybg01jDc8yHFypQOoYrzdXCrXkUjl1AqfMd/MqqAF+eABu1OcfP5a6nZlhbk83iG4zlHzqwnhqEBxOfHMLR9j++aGCoXXSsws=,iv:hlLcQYGWT/8J8tckpBc1iVx/m7UZJ1faBGja4gmh97c=,tag:nNYtMNAEYTPOoj45hjYnIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
