---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: static-iot-esphome
  namespace: home
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno1.10",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
          { "address": "10.4.0.102/24" }
        ]
      }
    }
