apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:I0MfDH9pg4stEG6JyNxwRaa++Shkg/OzT1VJTCe4STL5i/9wRp1OFQ==,iv:D1yRTjemXM75Ejbjf/wklh504FLl33Bk0GSjdz0j40I=,tag:ltUdfchyBezgcI9KGHohNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dn0elwr6a32pdjspgz733zgwdmyur98wcmcadhdhkzwudp7g4uuq8ty9ff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeExQUFRXUnhaR3U4VCs5
            OXBXTGlLRkdNQzVuZEg1MGo4TWNVNDRDZ0FzCnNxc3FnbHl3b1lYeGZKcFRudGs1
            MXY4a0xLWDFkRVZJdStTQXBDNDFHY3cKLS0tIEdmV2xQYVYxakNZdWdNMzRMR3RY
            VkhyMkN1NTZWVmVOa1VsNE9YK25yZlEKI5nLL1hopBJNdXgmu22BuxD/cRaszha0
            SMczSduY49zv+gOogwXLRE+mrXmKRw71HI1e0XM1J4hliE9JwA+Yng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T15:05:24Z"
    mac: ENC[AES256_GCM,data:w+I13glgneS88v6Drd13RIixnvHC8Ncfr/rBGKFqdrp3QJLKZVrVeEUxrLiP1Gy9lfmxGBAj7wQkWUszf7ZrqrjmdcVfemmcZRFtsGExpol6X0zHmkwRs++0OUof2/NAgRGvNEUsQ+CyqnEQzWMnYg/gYhAVN6DDUBRHK6z7BMo=,iv:RtJ4AQ/MZz0hKfz6UrmlLrmDNTtwae06ssQ3VUatEoU=,tag:CZSXZf5cX57LkzEEszdlkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
