apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-iot",
      "plugins": [
        {
          "type": "vlan",
          "master": "bond0",
          "vlanId": 10,
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "10.3.0.0/24", "gw": "10.3.0.1" }
            ]
          }
        },
        {
          "type": "macvlan",
          "mode": "bridge",
          "master": "@link",
          "capabilities": {
            "ips": true
          }
        },
        {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }
