apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:75/5YKK+rzimUllrdlWRjJTKvv+QcZNd9kOD6lWnL5AZn0ttLg==,iv:nhx22V5NGbLflIFI5SLAAJ3XAhbDHyKlOlu9hsJA4MU=,tag:4AZSFRZ2a558YVv2lBJyBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dn0elwr6a32pdjspgz733zgwdmyur98wcmcadhdhkzwudp7g4uuq8ty9ff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqc2pNMWQrTUNsd0tmN1Mv
            Zm5tT0NNcUJyK3YrWGpxeFQxYmdNY3ZvQW1jCmpialU1eTd0QUw2LzNncVN2c2Zv
            eW5aODZlL091eHk4WUpENktqVVZ5QzgKLS0tICt0SThsOHZoRithVE5VYUt3MHVJ
            OXN2bWFQdkpkbFVZalVwcUU4YzhHdk0KrgDEIH/xQQy+OT0xsopk/NThCFqdO3DG
            0RPNsEoElXayVEulcVouIGt1mw/aAai2SCOr/vSwFdl6IHeZg77oCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T12:23:30Z"
    mac: ENC[AES256_GCM,data:ekfrLUy+Fl5eLUMvrSMBX2015BnClPNwB8Ic0ZbggNFCkX8c0IhcYlOzQpVCIKCmbruovgtMJt8PI2x30ypOI6w1VcuK1ce9pP/yTzNc5kJBVUrOTjWB0bEFiZl7sXWCQwzbVjwZssGZxP2o5dNJX4xveMIVXOm7C3Q0d6OLGT0=,iv:VBzGcYd5wmHs7gdGR9KIoflXHe1yCoAem3emKVhYDtc=,tag:agYXSvvNkEIv38tMgCjKCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
