apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:t8iLHgZ4X0PXehTdLCbgq2OIws3I/BPob17W7nFOFgIiyhIl1X+odA==,iv:Z+OOA3d9g0tH4FQ+aBs9lrbYgi9PsiXRo1nW3H+MMkI=,tag:pvL3cGx+WfuWB13iYYyT7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dn0elwr6a32pdjspgz733zgwdmyur98wcmcadhdhkzwudp7g4uuq8ty9ff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNlBJdVBKcTBKeXhTdFJC
            SXhhTU8vWEtueWpkY3NLaG52Nkc1aVlHQ2lzCm1aZkhPYVkrcStvL1NxMjRLNTl5
            czZnVG81T1I5dHZCbHJ0bzRYbC9qUGcKLS0tIDZEcG1uR2xwd3pZK3MyMG1aUEVp
            VGI4ZUMvdlVaK1hmNXZrUFlZK25QYk0KXNIJY6RGfu15U8U/zcFGX8Z0Z6kIHdoU
            Ts+LPhIJOYghsFgeXuJ9jyN1WlGtOycgax+u/C3Mo07UlkAogVUWXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T12:45:10Z"
    mac: ENC[AES256_GCM,data:Ofx0jtvPXtHISL5RgFvlkYfu5+sA7t7LFluzNam/ERuBYG4NBHXfW23EloKefoxb5YLl5jun3lVFcyOffaxna7sq4MoPexT8CadE/KwJHjjHzIbvAzmfcT1GQ7uYrlGfxT78uSIx53ZDpip0LgSTbM7PgOtdEW1zNo2wsVo0i3A=,iv:4ZfYgvqxa3oNxyZjf6UphmbhaccenO15j10cHPDTnUA=,tag:Ji6Cgf+PP7kA+MD4iESaPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
