apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:G7u3rNSsIPYHDZjp9rHiNo/cuXCgjrAiVk2Xz4cfzNr8o5GFd05qPQ==,iv:9T4WnG/6JSWXEF1UoQEQxy5cJj7GutzEyZgVFLABlPw=,tag:kZDXdArbD1wBTifArw6IcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dn0elwr6a32pdjspgz733zgwdmyur98wcmcadhdhkzwudp7g4uuq8ty9ff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONXR6bmlmMUdPVHp2aWZX
            dk80bUZCUS9CTk9TVWZ0ekR2bk1BVXpoZVM4CmJZbUYzNmJpQ21ucmtJMzdyaElW
            TWpucE5zTjA3SFoyN0wrQ2dHdmNnd0kKLS0tIDlHYTNyRzJTeWFhZDRxZll3bXVy
            ajh0SXdKRnlUOTBTZVFheWtVUEk0VVkKQqMpXzuZ6lcwWATcVKDd5hJDbK4SbYoP
            mT3af+hjguAC+3QejZe1G/IPJilxmW3vrIc7sVoLmGUnO470BuSq4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T12:56:43Z"
    mac: ENC[AES256_GCM,data:PzNV4/AnFfcWuNWxMYESfFDoK5krtRHysFPDZ+MiwxNzs3Yp7jmCaN1YWAGnU8/2tbpJR5rvCU01ToJgyCzVbH6egQn0EKP5oZQm9u9M1Syp/66HqTd0+dWqAZzH61BWBYOT4UnsTw9ciYsYze1MMS2NWcdd+Uuaq3I0k5Fj6hE=,iv:1jAWqZNyzGmSe6M03PR978FNNeBqHXa2AjR3spfBSow=,tag:XJcSbh+tkOmj/ymz8Mf8nA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
