---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: true
    mayastor:
      localpv-provisioner:
        # -- Enables the openebs dynamic-localpv-provisioner. If disabled, modify etcd and loki-stack storage class accordingly.
        enabled: true
        hostpathClass:
          # -- Enable default hostpath localpv StorageClass.
          enabled: false
        analytics:
          enabled: false
    # openebs-crds:
    #   csi:
    #     volumeSnapshots:
    #       enabled: false
    # localpv-provisioner:
    #   localpv:
    #     image:
    #       registry: quay.io/
    #   helperPod:
    #     image:
    #       registry: quay.io/
    #   hostpathClass:
    #     enabled: true
    #     name: openebs-hostpath
    #     isDefaultClass: false
    #     basePath: /var/openebs/local
