---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: true
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
    localpv-provisioner:
      localpv:
        image:
          registry: quay.io/
      helperPod:
        image:
          registry: quay.io/
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: true
        basePath: /var/openebs/local
    # Refer to https://github.com/openebs/mayastor-extensions/blob/v2.7.1/chart/values.yaml for complete set of values.
    mayastor:
      obs:
        callhome:
          enabled: false
      loki-stack:
        enabled: false
      csi:
        node:
          initContainers:
            enabled: false
      etcd:
        # -- Kubernetes Cluster Domain
        clusterDomain: cluster.local
        localpvScConfig:
          enabled: true
          # Name of etcd's localpv hostpath storage class.
          name: "mayastor-etcd-localpv"
          # -- Host path where local etcd data is stored in.
          # -- ReclaimPolicy of etcd's localpv hostpath storage class.
          reclaimPolicy: Delete
          # -- VolumeBindingMode of etcd's localpv hostpath storage class.
          volumeBindingMode: WaitForFirstConsumer
        # Pod labels; okay to remove the openebs logging label if required
      localpv-provisioner:
        enabled: false
      crds:
        enabled: true
